version: '3.8'

services:
  backend_fs:
    build: ./backend
    container_name: backend_fs
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    expose:
      - "8080"
    ports:
      - "8080:8088"
    networks:
      - app-network

  frontend_fs:
    build: ./frontend
    container_name: frontend_fs
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3002"
    networks:
      - app-network
    depends_on:
      - backend_fs

networks:
  app-network:
    driver: bridge