version: '3.8'

services:
  backend_fs:
    build: ./backend
    container_name: backend_fs
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    expose:
      - "8080"
    networks:
      external:
        - app-network

  frontend_fs:
    build: ./frontend
    container_name: frontend_fs
    restart: always
    expose:
      - "80"
    networks:
      external:
        - app-network
    depends_on:
      - backend_fs

volumes:
  npm_data:
  npm_letsencrypt:

networks:
  app-network:
    driver: bridge