spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:mysql://171.244.142.43:3306/fashion_system
spring.datasource.username=root
spring.datasource.password=slm123slm123

# JPA (Hibernate) Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT's key
constant.key.signer-key=h1+1yyey6bWbtUuFTU24M8b+ARF0h0vv8rbuj+ncR6KdByL332FDZ72pEtEy+2Mz